quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:postgres}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:postgres}
quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${QUARKUS_CORS_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,*}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

