apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challengr-ingress
  annotations:
    # adjust annotations depending on the cluster ingress controller (example for nginx)
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: it220257.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: challengr-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: challengr-frontend
                port:
                  number: 80
