apiVersion: v1
kind: Secret
metadata:
  name: challengr-secrets
  namespace: student-it220257
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_CLIENT_SECRET: <replace-with-keycloak-client-secret>
