FROM eclipse-temurin:21-jre

RUN mkdir -p /opt/application
COPY target/quarkus-app/lib/ /opt/application/lib/
COPY target/quarkus-app/*.jar /opt/application/
COPY target/quarkus-app/app/ /opt/application/app/
COPY target/quarkus-app/quarkus/ /opt/application/quarkus/

WORKDIR /opt/application
CMD [ "java", "-Dquarkus.profile=prod", "-jar", "quarkus-run.jar" ]
